# ~/.bash_profile — managed by dotfiles (https://github.com/mikecuoco/dotfiles)
# Main entry point for login shells.
# Do NOT edit this file directly; put local overrides in ~/.extra.
# Re-run `dotfiles install` after updating the package.

# ── Shell options ─────────────────────────────────────────────────────────────

# Enable history expansion: typing !!<space> expands to the last command
bind Space:magic-space 2>/dev/null

# History: large, timestamped, deduped, appended (not overwritten)
export HISTTIMEFORMAT='%F %T '
export HISTCONTROL="ignoredups"
export HISTSIZE=100000
export HISTFILESIZE=$HISTSIZE
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"
type shopt &>/dev/null && shopt -s histappend cmdhist

# Sync history across terminal sessions in real-time
export PROMPT_COMMAND="history -a; history -c; history -r; ${PROMPT_COMMAND:-}"

# Better globbing and cd
type shopt &>/dev/null && shopt -s nocaseglob cdspell globstar 2>/dev/null

# ── Man page colors ────────────────────────────────────────────────────────────
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode (info box)
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# ── Common dotfiles ────────────────────────────────────────────────────────────
for _df_file in "$HOME"/.{exports,aliases,functions,bash_prompt}; do
    [ -r "$_df_file" ] && source "$_df_file"
done
unset _df_file

# ── Platform overlay ───────────────────────────────────────────────────────────
# `dotfiles install` writes the active profile name to ~/.config/dotfiles/profile
# and installs overlay files as ~/.exports.<profile>, ~/.aliases.<profile>, etc.
_DF_PROFILE="${DOTFILES_PROFILE:-$(cat "$HOME/.config/dotfiles/profile" 2>/dev/null)}"
if [ -n "$_DF_PROFILE" ]; then
    for _df_file in "$HOME"/.{exports,aliases,functions}."$_DF_PROFILE"; do
        [ -r "$_df_file" ] && source "$_df_file"
    done
fi
unset _DF_PROFILE _df_file

# ── Jump tool: zoxide (preferred) or z ────────────────────────────────────────
if command -v zoxide &>/dev/null; then
    eval "$(zoxide init bash)"
elif [ -f "$HOME/.z.sh" ]; then
    source "$HOME/.z.sh"
fi

# ── Bash completion ───────────────────────────────────────────────────────────
if [[ -n "$ZSH_VERSION" ]]; then   # bail out if running under zsh
    return 1 2>/dev/null || exit 1
fi
[ -f /etc/bash_completion ] && source /etc/bash_completion
# Download git-completion on first use if missing
if [ ! -f "$HOME/.git-completion.bash" ]; then
    _gc_url="https://raw.githubusercontent.com/git/git/HEAD/contrib/completion/git-completion.bash"
    if command -v curl &>/dev/null; then
        curl -fsSL "$_gc_url" -o "$HOME/.git-completion.bash" 2>/dev/null || true
    fi
    unset _gc_url
fi
[ -f "$HOME/.git-completion.bash" ] && source "$HOME/.git-completion.bash"
# Enable `g` alias tab-completion (same as git)
if type __git_complete &>/dev/null; then
    __git_complete g __git_main 2>/dev/null
fi

# ── Local overrides (not in git) ──────────────────────────────────────────────
[ -f "$HOME/.extra" ] && source "$HOME/.extra"
